# LightGCN, TopNModel, TopNPersonalized, TopNNearestModel, iALS
MODEL: TopNNearestModel
USE_TENSORBOARD: False

NUM_RAT_FOR_ITEM: 5
NUM_RAT_FOR_USER: 5
N_NEGATIVES: 20

METRICS_REPORT: [1, 10, 20]
EVAL_EPOCHS: 50

TRAIN_EPOCHS: 1000

# LightGCN config
LATENT_DIM: 64
N_LAYERS: 3
BPR_REG_ALPHA: 0.001

# TopNModel config
TOP_N: 100

# iALS config
ALS_N_ITERATIONS: 50
ALS_N_FACTORS: 64

# Gowalla dataset config
SPLIT_DATE: 2009-11-01
TEST_DAYS: 15
VAL_DAYS: 15