# LightGCN, TopNModel
MODEL: LightGCN
USE_TENSORBOARD: True

NUM_RAT_FOR_ITEM: 5
NUM_RAT_FOR_USER: 5
N_NEGATIVES: 20

METRICS_REPORT: [1, 10, 20]
EVAL_EPOCHS: 50

TRAIN_EPOCHS: 1000

# LightGCN config
LATENT_DIM: 64
N_LAYERS: 3

# TopNModel config
TOP_N: 100